# Generated by Django 3.2.4 on 2021-08-09 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('Title', models.CharField(max_length=35)),
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsideBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_id', models.IntegerField()),
                ('SubTitle', models.CharField(max_length=35)),
                ('CardBody', models.TextField(max_length=500)),
                ('board_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
    ]
